server:
  servlet:
    context-path:
      /api/users
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prueba
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
